sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    sources:
    packages:
    - python-dev
    - python-pip
    - libhdf5-serial-dev

install:
  - python setup.py install

script:
  - py.test --version #dummy

