sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
    - check
    - python-dev

install:
  - python setup.py install

script:
  - py.test -v

